### ISSUE TITLE
Change the cursor to indicate possible actions

### ISSUE THREAD

**Issue by w0rm** [w0rm/elm-pool#12]
https://developer.mozilla.org/en-US/docs/Web/CSS/cursor

Some ideas: 

* Hovering on the ball to pick the hitpoint - pointer
* When mouse is pressed on ball - ns-resize to set cue elevation
* When placing a ball in hand - pointer and no-drop (depending on the state)
* Simulation - wait

Originally proposed by @razzeee 😄

**Comment by absynce** [comment]
Good idea! My only concern is that it creates more of a desktop-focused design vs. other devices, like a tablet or phone.

**Comment by w0rm** [comment]
@absynce I think that for the the desktop MVP this could be a nice little trick to improve the UI. 

If we wanted to support mobile, we would need to do quite a lot of work anyway:

- zooming with pinch instead of scroll
- a visual button to shoot instead of the spacebar

**Comment by absynce** [comment]
That's true. It's an easy win for the desktop.
