### ISSUE TITLE
Overlay player/target on screen

### ISSUE THREAD

**Issue by absynce** [w0rm/elm-pool#5]
Show the current player and target (open, or solids/stripes) on the screen.

Font ideas:
- [Teko](https://fonts.google.com/specimen/Teko?preview.text=Player%201%20-%20Solids&preview.text_type=custom)

![image](https://user-images.githubusercontent.com/289969/102680712-5bff2800-4180-11eb-9104-a8ba283e5c56.png)

**Comment by absynce** [comment]
What do you think?
![image](https://user-images.githubusercontent.com/289969/102705793-e57e2b00-4250-11eb-82e0-bf0c6efe514c.png)

**Comment by w0rm** [comment]
@absynce looks great!
